import type { Dialect } from './dialects';

/**
 * The schedules offered by editor completion, per dialect.
 *
 * Deliberately three lists rather than one list reshaped: a five-field schedule is not a
 * six-field one with a zero on the front, and EventBridge needs a `?` in exactly one of the
 * two day fields. No descriptions are stored here -- they are generated by parseCron at
 * display time, so the completion popup and the hover can never disagree.
 */
const UNIX: string[] = [
	'* * * * *',
	'*/5 * * * *',
	'*/10 * * * *',
	'*/15 * * * *',
	'*/30 * * * *',
	'0 * * * *',
	'0 */2 * * *',
	'0 */6 * * *',
	'0 0 * * *',
	'0 3 * * *',
	'0 9 * * *',
	'0 12 * * *',
	'0 9 * * 1-5',
	'0 18 * * 1-5',
	'0 0 * * 0',
	'0 0 * * 1',
	'0 0 * * 6,0',
	'0 0 1 * *',
	'0 0 1,15 * *',
	'0 0 1 1 *',
	'30 2 * * 6',
	'@hourly',
	'@daily',
	'@weekly',
	'@monthly',
	'@yearly'
];

const SECONDS: string[] = [
	'* * * * * *',
	'*/10 * * * * *',
	'*/30 * * * * *',
	'0 * * * * *',
	'0 */5 * * * *',
	'0 */15 * * * *',
	'0 */30 * * * *',
	'0 0 * * * *',
	'0 0 */6 * * *',
	'0 0 0 * * *',
	'0 0 3 * * *',
	'0 0 9 * * *',
	'0 0 9 * * MON-FRI',
	'0 0 18 * * MON-FRI',
	'0 0 0 * * SUN',
	'0 0 0 * * MON',
	'0 0 0 1 * *',
	'0 0 0 1 1 *',
	'0 30 2 * * SAT'
];

const EVENTBRIDGE: string[] = [
	'*/5 * * * ? *',
	'*/15 * * * ? *',
	'0 * * * ? *',
	'0 */6 * * ? *',
	'0 0 * * ? *',
	'0 3 * * ? *',
	'0 12 * * ? *',
	'0 9 ? * 2-6 *',
	'0 18 ? * 2-6 *',
	'0 0 ? * 1 *',
	'0 0 ? * 2 *',
	'0 0 1 * ? *',
	'0 0 1 1 ? *',
	'0 0 L * ? *'
];

export function presets(dialect: Dialect): string[] {
	switch (dialect) {
		case 'seconds':
			return SECONDS;
		case 'eventbridge':
			return EVENTBRIDGE;
		default:
			return UNIX;
	}
}
